# Generated by Django 4.0.3 on 2022-04-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_edad_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='motivo',
            field=models.CharField(choices=[('EM', 'Evento Empresarial'), ('DE', 'Despedida Empresarial'), ('DEE', 'Desayuno Empresarial'), ('AL', 'Almuerzo')], max_length=32, verbose_name='Motivo del evento'),
        ),
    ]
