# Generated by Django 4.0.3 on 2022-04-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_evento_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateField(verbose_name='Fecha de evento'),
        ),
    ]
